---
sudo: required
services:
- docker
script:
- pip install molecule 
- cd tests 
- molecule test 
notifications:
    webhooks: 'https://galaxy.ansible.com/api/v1/notifications/'
...
# vim: ft=ansible:
