---
sudo: required
language: python
services:
  - docker
before_script:
  - pip install molecule docker
script:
  - cd files
  - docker build .
notifications:
    webhooks: 'https://galaxy.ansible.com/api/v1/notifications/'
...
# vim: ft=ansible:
