---
- name: 'Set some required facts.'
  set_fact:
    tower_package_name: 'ansible-tower'
    tower_package_version: '3.1.3'
    tower_package_release: '1'
- name: 'Make sure root user has ssh keys.'
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 8192
  register: keys
- name: "Add the new public key to the user's authorized list."
  authorized_key:
    user: root
    state: present
    key: "{{ keys.ssh_public_key }}"
- name: 'Install the missing language pack.'
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - language-pack-en
- name: 'Run the check static config.'
  include: ../tasks/check_static_config.yml
...
# vim: ft=ansible:
