---
- name: 'Install postgres.'
  apt:
    name: "{{ item }}" 
    state: present
    update_cache: yes 
  with_items:
  - postgresql-9.5
  - postgresql-server-dev-all
- name: 'Unarchive the ansible tower demo.'
  unarchive:
    src: https://s3-us-west-2.amazonaws.com/archive.gahan-corporation.com/ansible-tower-setup-latest.tar.gz 
    dest: /tmp
    copy: no
...
# vim: ft=ansible: 
