---
- name: 'Make sure root user has ssh keys.'
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 8192
  register: keys
- name: "Add the new public key to the user's authorized list."
  authorized_key:
    user: root
    state: present
    key: "{{ keys.ssh_public_key }}" 
- name: 'Install the missing language pack.'
  apt:
    name: "{{ item }}" 
    state: present
    update_cache: yes 
  with_items:
  - language-pack-en
- name: 'Update the inventory with a group for Tower.'
  template:
    dest: /etc/ansible/hosts
    src: hosts
- name: 'Check the static configuration.'
  include: check_config_static.yml
#- name: 'Start the Tower install process.'
#  include: tower/install.yml
...
# vim: ft=ansible: 
