---
- name: 'Make sure root user has ssh keys.'
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 8192
  register: keys
- name: "Add the new public key to the user's authorized list."
  authorized_key:
    user: root
    state: present
    key: "{{ keys.ssh_public_key }}"
- name: 'Install the missing language pack.'
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes 
  with_items:
  - language-pack-en
- name: 'Start the Tower install process.'
  include: includes/install.yml
...
# vim: ft=ansible:
