---
- name: 'Set some required facts.'
  set_fact:
    tower_package_name: 'ansible-tower'
    tower_package_version: '3.1.3'
    tower_package_release: '1'
- name: 'Make sure root user has ssh keys.'
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 8192
  register: keys
- name: "Add the new public key to the user's authorized list."
  authorized_key:
    user: root
    state: present
    key: "{{ keys.ssh_public_key }}"
- name: 'Install the missing language pack.'
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes 
  with_items:
  - language-pack-en
<<<<<<< HEAD
- name: 'Start the Tower install process.'
  include: includes/install.yml
=======
- name: 'Update the inventory with a group for Tower.'
  template:
    dest: /etc/ansible/hosts
    src: hosts
- name: 'Check the static configuration.'
  include: check_config_static.yml
  tag: check_config_static
#- hosts: tower:database
#  roles:
#    - role: check_config_static
#      check_config_static_required_vars:
#        - tower_package_name
#        - tower_package_version
#        - tower_package_release
#- name: "Group nodes by OS distribution"
#  hosts: all
#  gather_facts: true
#  tasks:
#    - name: group hosts by distribution
#      group_by: 
#        key: "{{ ansible_distribution }}-{{ ansible_distribution_version }}"
#      changed_when: false
#- name: 'Start the Tower install process.'
#  include: tower/install.yml
>>>>>>> d0c0d3835f6a0939b19c4ef79f7659f819671ae5
...
# vim: ft=ansible:
